### ISSUE TITLE
license is so unclear

### ISSUE THREAD

**Issue by IMS212** [DanielGolan-mc/Elderion#3]
are we even allowed to make pull requests??? this license is not in any way usable in court, and can not be held up in any case.

**Comment by Bubblie01** [comment]
yeah lmao what is a supreme license you may want to actually add more information

**Comment by DanielGolan-mc** [comment]
I'll just change to MIT.

**Comment by IMS212** [comment]
(Basically: please use an actual legal license from https://choosealicense.com, otherwise It will not hold up in any way)

**Comment by Jamalam360** [comment]
Don't forget to change the about me on GitHub to reflect that change

**Comment by IMS212** [comment]
Thanks!

**Comment by DanielGolan-mc** [comment]
You are welcome!
